In [1]:
import cortex
import numpy as np

In [2]:
cortex.align.automatic?

In [3]:
cortex.db.get_surf?

In [4]:
cortex.db.get_surf('C19_004', 'fiducial', 'lh')

(array([[ -14.231725  , -102.47507   ,    0.76951885],
        [ -14.647242  , -102.53186   ,    0.7280569 ],
        [ -14.6107435 , -102.17998   ,    1.9708266 ],
        ...,
        [ -19.217297  ,   67.432106  ,   23.18974   ],
        [ -18.741251  ,   68.15909   ,   21.461918  ],
        [ -19.073725  ,   67.96456   ,   21.703815  ]], dtype=float32),
 array([[     7,      1,      4],
        [     0,      1,      6],
        [     7,      6,      1],
        ...,
        [138191, 138192, 138537],
        [138191, 138537, 138816],
        [138537, 138829, 138816]], dtype=int32))

In [13]:
(vertices_lh, tri_lh), (vertices_rh, tri_rh) = cortex.db.get_surf('C19_004', 'fiducial', 'both')

In [4]:
vertices_lh.shape, vertices_rh.shape

((140080, 3), (140410, 3))

In [23]:
activations = np.random.randn(vertices_lh.shape[0] + vertices_rh.shape[0])

In [24]:
activations.shape

(280490,)

In [25]:
vertex = cortex.Vertex(activations, 'C19_004')

In [24]:
cortex.Volume?

In [26]:
cortex.webgl.show(vertex)

Started server on port 28151


<JS: window.viewer>

In [27]:
activations2 = np.ones(vertices_lh.shape[0] + vertices_rh.shape[0])*0

In [33]:
activations2[0:1000] = 1

In [34]:
activations2[0:10] = 2

In [36]:
vertex2 = cortex.Vertex(activations2, 'C19_004')

In [37]:
cortex.webgl.show(vertex2)

Started server on port 5771


<JS: window.viewer>

In [18]:
cortex.db.get_surfinfo?

In [20]:
c = cortex.db.get_surfinfo('C19_004', 'curvature')

In [21]:
cortex.webgl.show(c)

Started server on port 27178


<JS: window.viewer>

In [36]:
d = {'curvature': c, 'random': vertex}

In [22]:
cortex.webgl.show(d)

NameError: name 'd' is not defined

Stopping server


In [38]:
cortex.VertexRGB()

In [42]:
vertices = np.vstack([vertices_lh, vertices_rh])

In [10]:
vertices.shape

(280490, 3)

In [46]:
v_rgb = cortex.VertexRGB(vertices[:,0], vertices[:,1], vertices[:,2], 'C19_004')

In [61]:
cortex.webgl.show(v_rgb)

Started server on port 22444


<JS: window.viewer>

In [45]:
v_rgb = cortex.VertexRGB(vertices[:,0], vertices[:,1], vertices[:,2], 'C19_004')

In [43]:
vertices

array([[ -14.231725  , -102.47507   ,    0.76951885],
       [ -14.647242  , -102.53186   ,    0.7280569 ],
       [ -14.6107435 , -102.17998   ,    1.9708266 ],
       ...,
       [   1.5549192 ,   38.101974  ,    5.6920443 ],
       [   1.4704175 ,   38.089256  ,    5.353463  ],
       [   1.9478831 ,   39.00309   ,    4.529333  ]], dtype=float32)

In [44]:
tri_lh

array([[     7,      1,      4],
       [     0,      1,      6],
       [     7,      6,      1],
       ...,
       [138191, 138192, 138537],
       [138191, 138537, 138816],
       [138537, 138829, 138816]], dtype=int32)

In [48]:
v_rgb

<RGB vertex data for (C19_004)>

In [49]:
vertices[:,0]

array([-14.231725 , -14.647242 , -14.6107435, ...,   1.5549192,
         1.4704175,   1.9478831], dtype=float32)

In [60]:
v_rgb.vertices[0,0:100000,0:2] = 0

In [58]:
v_rgb.red.vertices

array([[-14.231725 , -14.647242 , -14.6107435, ...,   1.5549192,
          1.4704175,   1.9478831]], dtype=float32)