In [1]:
import cortex
import numpy as np

In [2]:
cortex.align.automatic?

In [3]:
cortex.db.get_surf?

In [2]:
cortex.db.get_surf('C19_004', 'fiducial', 'lh')

(array([[ -14.231725  , -102.47507   ,    0.76951885],
        [ -14.647242  , -102.53186   ,    0.7280569 ],
        [ -14.6107435 , -102.17998   ,    1.9708266 ],
        ...,
        [ -19.217297  ,   67.432106  ,   23.18974   ],
        [ -18.741251  ,   68.15909   ,   21.461918  ],
        [ -19.073725  ,   67.96456   ,   21.703815  ]], dtype=float32),
 array([[     7,      1,      4],
        [     0,      1,      6],
        [     7,      6,      1],
        ...,
        [138191, 138192, 138537],
        [138191, 138537, 138816],
        [138537, 138829, 138816]], dtype=int32))

In [3]:
(vertices_lh, tri_lh), (vertices_rh, tri_rh) = cortex.db.get_surf('C19_004', 'fiducial', 'both')

In [4]:
vertices_lh.shape, vertices_rh.shape

((140080, 3), (140410, 3))

In [5]:
activations = np.random.randn(vertices_lh.shape[0] + vertices_rh.shape[0])

In [6]:
activations.shape

(280490,)

In [7]:
vertex = cortex.Vertex(activations, 'C19_004')

In [8]:
cortex.Volume?

In [9]:
cortex.webgl.show(vertex)

Started server on port 48296


<JS: window.viewer>

In [11]:
activations2 = np.ones(vertices_lh.shape[0] + vertices_rh.shape[0])*0

NameError: name 'vertices_lh' is not defined

In [13]:
activations2[0:1000] = 1

In [14]:
activations2[0:10] = 2

In [10]:
vertex2 = cortex.Vertex(activations2, 'C19_004')

NameError: name 'activations2' is not defined

In [16]:
cortex.webgl.show(vertex2)

Started server on port 36315


<JS: window.viewer>

In [18]:
cortex.db.get_surfinfo?

In [10]:
c = cortex.db.get_surfinfo('C19_004', 'curvature')

In [16]:
cortex.webgl.show(c)

Started server on port 61037


<JS: window.viewer>

In [11]:
d = {'curvature': c, 'random': vertex}

In [ ]:
cortex.webgl.show(d)

In [9]:
cortex.VertexRGB()

TypeError: __init__() missing 3 required positional arguments: 'red', 'green', and 'blue'

In [12]:
vertices = np.vstack([vertices_lh, vertices_rh])

In [13]:
vertices.shape

(280490, 3)

In [14]:
v_rgb = cortex.VertexRGB(vertices[:,0], vertices[:,1], vertices[:,2], 'C19_004')

In [15]:
cortex.webgl.show(v_rgb)

Started server on port 65131


<JS: window.viewer>

Stopping server
Stopping server


In [45]:
v_rgb = cortex.VertexRGB(vertices[:,0], vertices[:,1], vertices[:,2], 'C19_004')

In [43]:
vertices

array([[ -14.231725  , -102.47507   ,    0.76951885],
       [ -14.647242  , -102.53186   ,    0.7280569 ],
       [ -14.6107435 , -102.17998   ,    1.9708266 ],
       ...,
       [   1.5549192 ,   38.101974  ,    5.6920443 ],
       [   1.4704175 ,   38.089256  ,    5.353463  ],
       [   1.9478831 ,   39.00309   ,    4.529333  ]], dtype=float32)

In [44]:
tri_lh

array([[     7,      1,      4],
       [     0,      1,      6],
       [     7,      6,      1],
       ...,
       [138191, 138192, 138537],
       [138191, 138537, 138816],
       [138537, 138829, 138816]], dtype=int32)

In [48]:
v_rgb

<RGB vertex data for (C19_004)>

In [49]:
vertices[:,0]

array([-14.231725 , -14.647242 , -14.6107435, ...,   1.5549192,
         1.4704175,   1.9478831], dtype=float32)

In [60]:
v_rgb.vertices[0,0:100000,0:2] = 0

In [58]:
v_rgb.red.vertices

array([[-14.231725 , -14.647242 , -14.6107435, ...,   1.5549192,
          1.4704175,   1.9478831]], dtype=float32)

In [39]:
cortex.webgl.show(v_rgb)

Started server on port 52044


<JS: window.viewer>

Stopping server


In [38]:
cortex.webgl.make_static('/Users/pinheirochagas/Desktop/browser', v_rgb, recache=True)

Generating new ctm file...
wm
wm
inflated
inflated


In [26]:
? cortex.webgl.make_static

In [36]:
import cortex

import numpy as np
np.random.seed(1234)

# gather data Volume
volume = cortex.Volume.random(subject='C19_004', xfmname='fiducial')

# select path for static viewer on disk
viewer_path = '/Users/pinheirochagas/Desktop/'

# create viewer
cortex.webgl.make_static(outpath=viewer_path, data=volume, recache=True)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/pinheirochagas/Pedro/drive/Stanford/lbcn_fMRI/C19_004/transforms/fiducial/matrices.xfm'

In [33]:
browser